# Generated by Django 4.1.3 on 2022-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_code_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='genre',
            field=models.CharField(choices=[('rock', 'rock'), ('pop', 'pop'), ('jazz', 'jazz'), ('classic', 'classic'), ('folk', 'folk')], default='', max_length=50),
        ),
    ]
