# Generated by Django 4.1.3 on 2022-12-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='genre',
            field=models.CharField(choices=[('rock', 'rock'), ('pop', 'pop'), ('jazz', 'jazz'), ('classic', 'classic'), ('folk', 'folk')], default='', max_length=50, null=True),
        ),
    ]
